# Generated by Django 3.0.7 on 2021-09-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Baking', 'Baking'), ('Baked', 'Baked'), ('Out of delivery', 'Out of delivery'), ('Order recieved', 'Order recieved')], default='Order Received', max_length=100),
        ),
    ]
